locals {
  st = lower("stblobfe${substr(md5(timestamp()), 0, 6)}")

  files = {
    readme.md = "# Generated by Terraform\n"
    app.json  = "{\"version\":\"1.0\",\"env\":\"dev\"}"
    note.txt  = "remember to destroy me"
  }
}

resource "azurerm_resource_group" "this" {
  name     = "rg-foreach-blobs"
  location = "eastus"
}

resource "azurerm_storage_account" "this" {
  name                     = local.st
  resource_group_name      = azurerm_resource_group.this.name
  location                 = azurerm_resource_group.this.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "cfg" {
  name                  = "config"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "file" {
  for_each             = local.files
  name                  = each.key
  storage_account_name  = azurerm_storage_account.this.name
  storage_container_name = azurerm_storage_container.cfg.name
  type                 = "Block"
  source_content       = each.value
}

output "blobs" { value = keys(azurerm_storage_blob.file) }
