# Lab 04 — for_each over a MAP of blobs.
# A map's values can be rich objects, not just strings. Here each blob has its
# own content. for_each iterates the map; each.key is the filename, each.value
# is the {content} object.
terraform {
  required_version = ">= 1.5.0"
  required_providers { azurerm = { source = "hashicorp/azurerm", version = "~> 3.70" } }
}
provider "azurerm" { features {} }

locals {
  st = lower("stblobfe${substr(md5(timestamp()), 0, 6)}")

  # A map keyed by filename → content. Each entry becomes one blob.
  files = {
    readme.md = "# Generated by Terraform\n"
    app.json  = "{\"version\":\"1.0\",\"env\":\"dev\"}"
    note.txt  = "remember to destroy me"
  }
}

resource "azurerm_resource_group" "this" {
  name     = "rg-foreach-blobs"
  location = "eastus"
}

resource "azurerm_storage_account" "this" {
  name                     = local.st
  resource_group_name      = azurerm_resource_group.this.name
  location                 = azurerm_resource_group.this.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "cfg" {
  name                  = "config"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "private"
}

# One blob per map entry. each.key = filename, each.value = content.
resource "azurerm_storage_blob" "file" {
  for_each             = local.files
  name                  = each.key
  storage_account_name  = azurerm_storage_account.this.name
  storage_container_name = azurerm_storage_container.cfg.name
  type                 = "Block"
  source_content       = each.value
}

output "blobs" { value = keys(azurerm_storage_blob.file) }
